### PR TITLE
stores naked tea binaries for direct download

### PR DESCRIPTION
**Pull request by jhheider**
Exactly like the title. Open the bottle, get the bin, store it appropriately.

Will require a rebuild of (at least) the last version of `tea` after merge.

### CODE REVIEW

**Comment by mxcl** [comment]
I’m sorry you did the work but this should be in tea/cli and not here. Even though that's more work.

These scripts are meant to be general and for the community. Yeah sure right now they're pretty specific to us. But I don't want us to play favorites like this. And in future these scripts will be templates for generalized pantries.

**Comment by jhheider** [comment]
Hm. That shouldn't be a problem. Seems a little unnatural, since it won't be the same binary that is in the bottle, but it should be the same build (obviously). Happy to move it there. Do you want it in the www bucket as well?

**Comment by jhheider** [comment]
Obviously, my original plan was just to unbottle in lambda, but their response size limitations make that unworkable.

**Comment by mxcl** [comment]
> Hm. That shouldn't be a problem. Seems a little unnatural, since it won't be the same binary that is in the bottle

We compile binaries in tea/cli’s CD too so we can attach them to releases so we're already building there too. Longer term the maintainers should be able to provide the binaries we use (to decentralize and remove stupid duplication), but right now this is pretty common so us doing it is also typical. Though less ideal for sure.

It's a case of picking trade offs. And keeping pantry.core generalized is a goal.

> Do you want it in the www bucket as well?

Like I guess that's probably the best idea, then there's no magic that may punish us in the future.

**Comment by jhheider** [comment]
Good point about release bins. I'll just copy them to www. That's easy.

**Pull request closed without merging**
