### PR TITLE
add `interprets:` key to appropriate packages

### PR DESCRIPTION
**Pull request by jhheider**
Adds `ts`, `js`, `pl`, `py`, `rb`, `go` interpreter keys to their respective packages.

### CODE REVIEW

**Comment by jhheider** [comment]
This is gonna build a lot of stuff, pretty unnecessarily. Can be canceled if desired.

**Comment by mxcl** [comment]
I think we should go with:

```yaml
.ts: [bin/deno, run]
.py: [bin/python]
```

Several mods here. Thoughts?

**Comment by jhheider** [comment]
Only issue is that bin keyed values won't be on the path when the environment is injected. Single line style arrays should be fine, of course.

**Comment by jhheider** [comment]
Giving this slightly more thought, we might want to change the `provides` key altogether to `executables` and assume the `bin/` prefix.

**Comment by mxcl** [comment]
I still think the `.` prefix makes what we mean clearly.

```yaml
.ts: [deno, run]
.py: python
```

You’re right about the `bin/` prefix. The inline arrays was just illustrative, but well in this case I think it's neater since the fact they are arrays is not as important as the arguments being read in one go.

**Comment by mxcl** [comment]
well thinking about it, no tool interprets things differently (currently…) so perhaps it would be better like so:

```yaml
interprets:
  extensions: [ts, js]
  args: [node, -e, $@]
```

`args` to be consistent with tea-script YAML front matter, but probably we should just figure out the right name now.

**Comment by jhheider** [comment]
All of these grammars could work. The last is definitely the most expressive. No consider the case where different extensions require different invocations. Array?

**Comment by jhheider** [comment]
More expressive syntax implemented:
```yaml
interprets:
  extensions: string | string[]
  args: string | string[]
```

**Comment by mxcl** [comment]
> Now consider the case where different extensions require different invocations. Array?

That would work. I think we can wait for a situation reported by the community that requires it tho.

**Pull request merged**
