### PR TITLE
codesigning

### LINKED ISSUE #21: Signed Binaries Apple In CD's
We need signed apple binaries in CD process. Apple Developer process has been completed.

### PR DESCRIPTION
**Pull request by jhheider**
This appears to work. Now... how to _really_ test it?

@mxcl, somewhere we seem to have broken fix-elf.ts: [log](https://github.com/teaxyz/pantry.core/actions/runs/3492610073/jobs/5846572338). It was last seen working in the wild rubygems rebuilt using tea@0.13.0 and pantry.core 99253c44678bd7329ec5dcd08e4d471ed42abdc6

resolves #21

### CODE REVIEW

**Comment by mxcl** [comment]
sweet. how do we test before going to prod?

Also fix-macho does some signing, maybe we don't need to now? Or should sign with this key.

**Comment by jhheider** [comment]
I believe fix-machos could skip local signing, but I didn't remove it as it should be non-harmful.

The testing is the question. If this should fix the quarantine issue, we'd need a CI test that builds the artifact, loads it on another Mac instance without clearing the quarantine bit, and sees if it runs. Maybe.

**Comment by mxcl** [comment]
I guess if you can just prove it works for a single test bottle we’ll flip the switch and cross fingers.

**Comment by mxcl** [comment]
so probs: build something that is easy to test, like wget and we can both download it and test on our local machines

**Comment by jhheider** [comment]
Simple artifact test passing with `go`, so let's merge and test broader.

**Pull request merged**
